### ISSUE TITLE
Minor question

### ISSUE THREAD

**Issue by abhishekaich27** [LiUzHiAn/hf2vad#1]
For this line:
https://github.com/LiUzHiAn/hf2vad/blob/abfde047f75586faf04ffe767ae53062b848bd63/utils/eval_utils.py#L74

is my following interpretation correct? I am trying to use this implementation in my work.

`truth` is ground truth labels with normal frames as `0` and anomaly frames as `1`, `preds` has (hopefully) lower value for normal frame and higher value for anomaly frames. `pos label=1` because the anomaly is `1` in ground truth labels.

**Comment by LiUzHiAn** [comment]
Yes, you are correct. The positive samples  are those abnormal frames we are interested.
