### ISSUE TITLE
weight of cascade RCNN

### ISSUE THREAD

**Issue by Sunxiaohu0406** [LiUzHiAn/hf2vad#14]
Hello! Thank you for your excellent work. I'm very interested in your work, but I encounter a problem in the preprocessing stage and can't find the preprocessing weight of cascade RCNN . Can you send a download link or upload this weight?

**Comment by LiUzHiAn** [comment]
please see https://github.com/LiUzHiAn/hf2vad/issues/2#issuecomment-922941324
