### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.dataset'

### ISSUE THREAD

**Issue by Pros-yanghaozhe** [LiUzHiAn/hf2vad#19]
I met the problem：
ModuleNotFoundError: No module named 'datasets.dataset'
when running ‘python extract_flows.py  --dataset_name=ped2 --mode=train’

**Comment by LiUzHiAn** [comment]
Please check where you are (i.e., the current working direction). Maybe you can change to the root directory, and run `python pre_process/extract_flows.py`. BTW, I used the Pycharm IDE, it works well with the provided instructions.

**Comment by ChiSrwi** [comment]
I also want to ask how to solve this problem. I want to know is that the root directory which is the directory of the project? Also I want to know what is the version of the datasets package?

**Comment by ChiSrwi** [comment]
@LiUzHiAn

**Comment by LiUzHiAn** [comment]
Moving the pre_process/extract_flows.py to the root dir and then executing it there would resolve the problem.  The root directory is where the train.py and eval.py are placed.

I temporally close this issue, feel free to reopen if you can't get around.
