### ISSUE TITLE
Test001_gt，Please help me

### ISSUE THREAD

**Issue by youngupup** [LiUzHiAn/hf2vad#22]
i want to konw Test001_gt is a folder（there is amat file or a txt file in it） or a txt file or a mat file？
Thank you！

**Comment by youngupup** [comment]
@LiUzHiAn

**Comment by LiUzHiAn** [comment]
please download the ped2 dataset here. http://www.svcl.ucsd.edu/projects/anomaly/UCSD_Anomaly_Dataset.tar.gz

**Comment by youngupup** [comment]
@LiUzHiAn Thank you so much！
