### ISSUE TITLE
About extracting optical flows

### ISSUE THREAD

**Issue by ChiSrwi** [LiUzHiAn/hf2vad#24]
When I try to run the command 
$ python extract_flows.py --proj_root=<path/to/project_root> --dataset_name=ped2 --mode=train
It is work but I didn't see anything about the flow in dataset so I just want to know what happen it is?

**Comment by ChiSrwi** [comment]
I think it is the problem of the dataset which I download in the link in the github is different with which you showed in github. Can you send me the old dataset to me?

**Comment by LiUzHiAn** [comment]
hi, please download the ped2 from their official page, see #22. 

I will find time to update the download link, thanks.
