### ISSUE TITLE
No module named 'resample2d_cuda'? 

### ISSUE THREAD

**Issue by wanlong111** [LiUzHiAn/hf2vad#30]
No module named 'resample2d_cuda'? Can you tell me how to solve it?

**Comment by lixiaoxiaozhao** [comment]
Hello, have you resolved this issue? I have also encountered an issue that cannot be resolved

**Comment by 1s3ss** [comment]
> No module named 'resample2d_cuda'? Can you tell me how to solve it?

Hi， I'm having the same issue, please how did you solve it！
