### ISSUE TITLE
Flow Reconstruction 

### ISSUE THREAD

**Issue by jooyeon-Yee** [LiUzHiAn/hf2vad#7]
If it's not an excuse, could you tell me the anomaly performance when I only do Flow Reconstruction in avenue?
In the paper, 86% came out, but the result I ran only came out 75%.
thank you.

**Comment by LiUzHiAn** [comment]
Hi,

What's your input size to FlowNet2? It should be 1024 * 768.

How did you do when evaluating the anomaly performance with flow recon. only?

**Comment by jooyeon-Yee** [comment]
oh i understand it, thank you very much!
