### ISSUE TITLE
Where is the chunked_samples <dict>?

### ISSUE THREAD

**Issue by DaffTangEclipse** [LiUzHiAn/hf2vad#8]
Where is the chunked_samples <dict>?
In datasets/dataset.py, the function  "Chunked_sample_dataset"  obtain a data dict,the keys are "appearance\motion\bbox\pred_frame\sample_id" ，but where are the keys and values?

**Comment by LiUzHiAn** [comment]
Please see the preprocessing steps to prepare the data, where the keys and values can be found,
